import type { Request, Response } from "express";
import { uploadToS3 } from "../services/s3.service.js";
import { analyzeImage } from "../services/ai.service.js";
import { checkCaptureLimit, incrementScreenshotUsage } from "../services/db.service.js";
// import { saveScreenshot, searchScreenshots, generateEmbedding } from "../services/db.service.js";  // DISABLED — using Cognee only
import { v4 as uuidv4 } from "uuid";
import cogneeService from "../services/cognee.service.js";
import { buildGraph } from "../agents/workflow/workflow.js";

type SearchMode="query"|"chatMode";
export const processScreenshot = async (req: Request, res: Response) => {
    try {
        const file = req.file;
        const { userId } = req.body;

        if (!file) {
            return res.status(400).json({ error: "No file uploaded" });
        }

        if (!userId) {
            return res.status(400).json({ error: "User ID is required" });
        }

        // ─── Check capture limit ─────────────────────────────────
        const limitCheck = await checkCaptureLimit(userId);

        if (!limitCheck.allowed) {
            return res.status(403).json({
                error: "limit_exhausted",
                message: `You've used all ${limitCheck.limit} free captures. Upgrade to continue capturing memories.`,
                plan: limitCheck.plan,
                used: limitCheck.used,
                limit: limitCheck.limit,
            });
        }

        // ─── Warn when only 1 capture remaining ──────────────────
        const warningThreshold = limitCheck.remaining === 1;

        const fileName = `${userId}_${Date.now()}_${uuidv4()}.png`;
        const mimeType = file.mimetype;

        // ── Step 1: Upload image to S3 ────────────────────────────
        const imageUrl = await uploadToS3(file.buffer, fileName, mimeType);

        // ── Step 2: AI Vision Analysis ────────────────────────────
        const analysis = await analyzeImage(file.buffer, mimeType);

        // ── Step 3: Save to Cognee memory layer ─────────────────
        // AstraDB vector store DISABLED — using Cognee only
        const cognee = new cogneeService();
        await cognee.Remember({
            user_id: userId,
            image_url: imageUrl,
            summary: analysis.summary,
            tags: analysis.tags,
            created_at: new Date().toISOString(),
        }, userId);

        // ── Step 4: Increment usage counter ───────────────────────
        await incrementScreenshotUsage(userId);

        console.log("Screenshot stored in Cognee:", analysis);

        res.status(200).json({
            message: "Screenshot processed successfully",
            warning: warningThreshold
                ? `⚠️ Only 1 capture left on your free plan. Upgrade to keep going!`
                : null,
            remaining: (limitCheck.remaining as number) - 1,
            data: { imageUrl, analysis },
        });
    } catch (error: any) {
        console.error("Error processing screenshot:", error);
        res.status(500).json({ error: error.message });
    }
};

export const handleSearch = async (req: Request, res: Response) => {
    try {
        const { query, userId, sessionId: clientSessionId } = req.body;
        const mode: SearchMode = req.body?.mode;

        console.log("Search request:", req.body);



        // sessionId is generated by the backend on the first message.
        // Frontend stores it and sends it back for follow-up messages
        // so Cognee groups them as one conversation.
        const sessionId = clientSessionId ?? uuidv4();

        console.log(`Search request: query="${query}", userId="${userId}", mode="${mode}", sessionId="${sessionId}"`);

        if (!query || !userId) {
            return res.status(400).json({ error: "Query and User ID are required" });
        }

        let results;

        // Always use Agent mode (LangGraph agent with dynamic tools)
        const agentGraph = await buildGraph(userId);
        const agentState = await agentGraph.invoke(
            {
                messages: [{ role: "user", content: query }],
                query,
                userId,
                sessionId,
                memories: [],
                gmail: [],
                notion: [],
                browser_search: [],
                photos: [],
                structuredResponse: [],
                answer: "",
            },
            {
                configurable: { userId, sessionId },
            }
        );

        results = {
            structuredResponse: agentState.structuredResponse,
            answer: agentState.answer,
            sessionId,
        };

        console.log(`Agent results: ${agentState.structuredResponse?.length ?? 0} images, answer length: ${agentState.answer?.length ?? 0}`);
        
        console.log("SENDING TO FRONTEND:", results);
        res.status(200).json({ results });
    } catch (error: any) {
        console.error("Error searching screenshots:", error);
        res.status(500).json({ error: error.message });
    }
};

export const debugCognee = async (req: Request, res: Response) => {
    try {
        const svc = new cogneeService();
        const result = await svc.Recall('aws', 'n2fXRwhkuDTSTr2nc5Hjl8Fdlke2');
        res.status(200).json({ raw: result });
    } catch (e: any) {
        res.status(500).json({ error: e.message });
    }
};
